# @name teste_get

GET http://127.0.0.1:8000/

###

# @name teste_get_infinity

GET http://127.0.0.1:8000/infinity


###

# @name exibir_dados

GET http://127.0.0.1:8000/meus-dados

###

# @name get_cursos
GET http://127.0.0.1:8000/cursos



###

# @name get_curso_by_id
GET http://127.0.0.1:8000/cursos/1


###

# @name get_curso_by_nota
GET http://0.0.0.0:8000/cursos-by-nota?nota=7


###

# @name post_curso
POST http://0.0.0.0:8000/cursos
Content-Type: application/json

{
    "codigo": 3,
    "nome": "FastAPI",
    "cargaHoraria": 40,
    "disponivel": true,
    "notaCorte": 8.5
}


###

# @name put_curso
PUT http://localhost:8000/cursos/1
Content-Type: application/json

{
    "codigo": 1,
    "nome": "FastAPI",
    "cargaHoraria": 40,
    "disponivel": true,
    "notaCorte": 8.5
}

###

# @name delete_curso
DELETE http://localhost:8000/cursos/1